### ISSUE TITLE
How hook execSQL method？

### ISSUE THREAD

**Issue by wyhuan** [mar-v-in/ArtHook#15]
how hook "android.database.sqlite.SQLiteDatabase->execSQL"？

I try fail

        File folder = this.getFilesDir();
        File f = new File(folder.getAbsolutePath() + "/test");
        SQLiteDatabase db = SQLiteDatabase.openOrCreateDatabase(f, null);
        String sql = ".......";
        db.execSQL(sql);

    @Hook("android.database.sqlite.SQLiteDatabase->execSQL")
    public void SQLiteDatabase_execSQL(String sql) throws SQLException {
        Log.e(TAG, "SQLiteDatabase_execSQL: " + sql);
        OriginalMethod.by("SQLiteDatabase_execSQL").invoke(sql);
    }

**Comment by mar-v-in** [comment]
What is not working? Be more precise!

You invoke the original method by identifier, but don't declare the identifier via `@BackupIdentifier("SQLiteDatabase_execSQL")`

**Comment by wyhuan** [comment]
I tried your way, but without success

    @Hook("android.database.sqlite.SQLiteDatabase->execSQL")
    @BackupIdentifier("SQLiteDatabase_execSQL")
    public void SQLiteDatabase_execSQL(String sql) throws SQLException {
        Log.e("neil", "SQLiteDatabase_execSQL: " + sql);
        OriginalMethod.by("SQLiteDatabase_execSQL").invoke(sql);
    }

Can you hook to this method？ 
android.database.sqlite.SQLiteDatabase->execSQL

You can try

    File folder = this.getFilesDir();
    File f = new File(folder.getAbsolutePath() + "/test");
    SQLiteDatabase db = SQLiteDatabase.openOrCreateDatabase(f, null);
    String sql = ".......";
    db.execSQL(sql);

**Comment by wyhuan** [comment]
I have solved the problem is to find the original function of the problem。3Q
