### ISSUE TITLE
Added support for Android O, i can hook System.currentTimeMillis but others disable

### ISSUE THREAD

**Issue by crtthas** [mar-v-in/ArtHook#22]
Added support for Android O, i can hook System.currentTimeMillis but others disable. Counld you tell me why?

**Comment by wyhuan** [comment]
ArtHooK getQuickCompiledCodeSize method ->Java_de_larma_arthook_Native_memget 
srcPnt:""
SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x8000112ec1b8c))
Have you ever met?
