### ISSUE TITLE
Some question for “thumb2” instruction

### ISSUE THREAD

**Issue by rockman1949** [mar-v-in/ArtHook#4]
This is amazing work! 
I have some question for you after I dig into the code.
1. https://github.com/mar-v-in/ArtHook/blob/master/lib/src/main/java/de/larma/arthook/instrs/Thumb2.java#45. why you use "ip" register for cmp?
2. https://github.com/mar-v-in/ArtHook/blob/master/lib/src/main/java/de/larma/arthook/instrs/Thumb2.java#47.   You annotation “bne next”， but I decode the “0x40, (byte) 0xf0, 0x09, (byte) 0x80,”  it was mean "bne #9". But 9 wasn't an instruction. Maybe I was made a mistake, Could you explain it more detail for me.  I know this “bne” shouldn't happen, but I still confused with this code！ 
   Thank you very much!

**Comment by rockman1949** [comment]
As questtion 2, There was a mistake,  “0x40, (byte) 0xf0, 0x09, (byte) 0x80" it was mean "bne #18", so it will jump to next "TargetJump", am I right?

**Comment by mar-v-in** [comment]
Question 1: We need to store the value to compare in a register. ip ("intra-procedural scratch register") is the only register that can be destroyed between method calls. Using ip means we don't need to backup the register, which is very fortunate as we can't guarantee that we can write to stack at this position without causing a stack corruption/overflow.

Question 2: Yes, your second comment is right about this statement. "next" is probably not perfect as comment.

**Comment by rockman1949** [comment]
Thank you！
