### ISSUE TITLE
crash on "arm64" device

### ISSUE THREAD

**Issue by rockman1949** [mar-v-in/ArtHook#6]
I test the testbed on arm64. 

09-27 01:29:04.525: I/DEBUG(500): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
09-27 01:29:04.525: I/DEBUG(500): Build fingerprint: 'HONOR/ATH-AL00/HWATH:5.1.1/HONORATH-AL00/C00B165:user/release-keys'
09-27 01:29:04.525: I/DEBUG(500): Revision: '0'
09-27 01:29:04.525: I/DEBUG(500): ABI: 'arm64'
09-27 01:29:04.525: I/DEBUG(500): pid: 18953, tid: 18953, name: ma.arthook.test  >>> de.larma.arthook.test <<<
09-27 01:29:04.525: I/DEBUG(500): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1856687630ce74
09-27 01:29:04.535: I/DEBUG(500):     x0   0000000000000001  x1   701856687630ce84  x2   0000000000000000  x3   0000000000000000
09-27 01:29:04.535: I/DEBUG(500):     x4   0000005574575c60  x5   0000000000000000  x6   00000055744f4f08  x7   0000000000000000
09-27 01:29:04.535: I/DEBUG(500):     x8   0000000000000000  x9   045f2eb74308f13a  x10  0000000000000000  x11  0000000000430000
09-27 01:29:04.535: I/DEBUG(500):     x12  0000000000550000  x13  0000000000430000  x14  0000000000000000  x15  0000007fb0bcd000
09-27 01:29:04.535: I/DEBUG(500):     x16  0000007fb0bcf470  x17  000000000000002e  x18  0000007fb0b1a000  x19  0000000000000008
09-27 01:29:04.535: I/DEBUG(500):     x20  701856687630ce74  x21  00000055745057b0  x22  0000000000000021  x23  701856687630ce74
09-27 01:29:04.535: I/DEBUG(500):     x24  0000000000000000  x25  0000000012ccf8e0  x26  0000000000000008  x27  0000000012c84210
09-27 01:29:04.535: I/DEBUG(500):     x28  0000000000000002  x29  0000007fcefdd8b0  x30  0000007faf503dd0
09-27 01:29:04.535: I/DEBUG(500):     sp   0000007fcefdd640  pc   0000007faf503fd4  pstate 0000000080000000
09-27 01:29:04.535: I/DEBUG(500): backtrace:
09-27 01:29:04.535: I/DEBUG(500):     #00 pc 0000000000000fd4  /data/app/de.larma.arthook.test-1/lib/arm64/libarthook_native.so (Java_de_larma_arthook_Native_memget+592)
09-27 01:29:04.535: I/DEBUG(500):     #01 pc 00000000000099e4  /data/dalvik-cache/arm64/data@app@de.larma.arthook.test-1@base.apk@classes.dex

I think it need to be add arm64 instruction.

**Comment by mar-v-in** [comment]
Arm64 support was added
